Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [5]:
import numpy as np

In [7]:
# create rank 1 matrix
a = np.array([1, 2, 3, 'shivam'])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(4,)

In [12]:
a[3]

'shivam'

In [13]:
a[2] = 5

In [14]:
a

array(['1', '2', '5', 'shivam'], dtype='<U11')

In [16]:
# create 2 dimension array
b = np.array([[4, 5, 6], [9, 8, 1]])

In [17]:
b

array([[4, 5, 6],
       [9, 8, 1]])

In [18]:
b.shape

(2, 3)

### Some Basic Operations

In [19]:
a = np.zeros((3,3))  # Create an array of all zeros
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
b = np.ones((3,3))   # Create an array of all ones
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
c = np.full((2,2), 5)  # Create a constant array
c

array([[5, 5],
       [5, 5]])

In [25]:
d = np.eye(3)    # Create a 2x2 identity matrix
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
e = np.random.random((3,3))   # Create an array filled with random values

In [27]:
e

array([[0.75201217, 0.91539365, 0.65411572],
       [0.14006457, 0.10156965, 0.9793622 ],
       [0.07888507, 0.41844092, 0.85773072]])

### Array Indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [28]:
a = ([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
a[2]

[7, 8, 9]

In [30]:
a[1:2]

[[4, 5, 6]]

In [31]:
a[:2]

[[1, 2, 3], [4, 5, 6]]

In [36]:
a[::2]

[[1, 2, 3], [7, 8, 9]]

**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [37]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [40]:
bool_idx = (a<3)
bool_idx

array([[ True,  True],
       [False, False],
       [False, False]])

In [41]:
a[bool_idx]

array([1, 2])

### Datatypes

In [42]:
x = np.array([1, 3, 8])
x.dtype

dtype('int32')

In [43]:
y = np.array([7.8, 6.0, 5.2])
y.dtype

dtype('float64')

In [44]:
z = np.array(['shivam', 'singh', 'renukoot'])
z.dtype

dtype('<U8')

### arange and linspace

In [48]:
a = np.arange(3, 18, 2.3)
a

array([ 3. ,  5.3,  7.6,  9.9, 12.2, 14.5, 16.8])

In [49]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [50]:
list(range(50,-1,5))

[]

In [51]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [52]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [53]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


### Random number generation

In [54]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.2796975  0.9290444  0.73990657]
 [0.00369839 0.79986594 0.51653624]]


In [55]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.28289848  1.78238668  2.7397961 ]
 [ 0.36277437 -0.96560005  0.82226769]
 [-1.2919711   0.30284643  0.67270476]
 [ 1.79120515 -1.42554729 -1.82797673]]


In [56]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

Random integer vector: 4

Random integer matrix


In [57]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[55 59  6  3]
 [62 20 84  5]
 [88 15 35 88]
 [ 2 42 26  7]]

20 samples drawn from a dice throw: [6 6 5 6 4 2 5 2 3 6 6 3 3 4 5 1 1 4 5 4]


### Array Math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [58]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [59]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [60]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [61]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [62]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [63]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [64]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [65]:
np.dot(x,v)

array([29, 67])

In [66]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [67]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [68]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [69]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [70]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [71]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [72]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [73]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [74]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


#### Here are some application of Broadcasting

In [75]:
# Compute outer product of vectors
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.